Feature/multiple servers
ttbud/ttbud pull request #462
Opened 2020-11-24 04:59 UTC by sburba

2020-11-24 19:09 UTC, sjohnson31 requested changes

2020-11-24 19:30 UTC, sburba commented on api/src/room_store.py
> +        if self.storage.lock_expiration_times.get(room_id, False) is not False:
Not really, since 0 is a valid expiration time and is falsy

2020-11-24 19:35 UTC, sburba commented on api/src/game_state_server.py
> +    async def _create_room(
That's a good point. It also doesn't necessarily create the room if it already exists. What about `_acquire_room`?

2020-11-24 19:48 UTC, sjohnson31 commented on api/src/room_store.py
> +        if self.storage.lock_expiration_times.get(room_id, False) is not False:
I don't know what you mean; we're in complete agreement here.

2020-11-24 19:48 UTC, sjohnson31 commented on api/src/game_state_server.py
> +    async def _create_room(
That's better. Perhaps `_aquire_room_slot`?

2020-11-24 20:46 UTC, sburba commented on api/src/room_store.py
> +        if self.storage.lock_expiration_times.get(room_id, False) is not False:
Oh I thought the first message was sarcasm

2020-11-25 00:47 UTC, sburba commented on api/src/game_state_server.py
> +    async def _create_room(
Sounds good. I've done that

2020-11-25 00:48 UTC, sburba commented on api/src/room_store.py
> +LOCK_EXPIRATION_SECS = 10
Yeah, I agree. I've moved it up

2020-11-25 02:10 UTC, sjohnson31 approved these changes

2020-11-25 02:27 UTC, merged